version: '3.8'

services:
  taskmanager-backend:
    image: danielllumigusin/taskmanager-backend:latest
    container_name: taskmanager-backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=task_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: taskmanager-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
    driver: local
